export { Header } from './Header'
export { Hero } from './Hero'
export { LogoCloud } from './LogoCloud'
export { Features } from './Features'
export { Testimonial } from './Testimonial'
export { Pricing } from './Pricing'
export { FAQ } from './FAQ'
export { CTA } from './CTA'
export { Footer } from './Footer'

